services:
  redis:
    image: redis
    restart: always
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    depends_on:
      - redis
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network: