name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20.18.2
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.2
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --check-files